const SHEET_ID="1_WsSmEpXcckIV9wbQp2K6YZe4jZ2XlX2Vt6lmXmfiHs";
const ADMIN_PASSWORD="0702";
const DEFAULT_SHEET_URL="https://docs.google.com/spreadsheets/d/"+SHEET_ID+"/export?format=csv&gid=0";
const BACKUP_SHEET_URL="https://docs.google.com/spreadsheets/d/"+SHEET_ID+"/gviz/tq?tqx=out:csv&gid=0";
const HTMLVIEW_SHEET_URL="https://docs.google.com/spreadsheets/d/"+SHEET_ID+"/htmlview";
const LOCAL_ROOM_URL="./room-list.csv";
let roomList=[], results={roomAll:[]}, currentTab="roomNot";
const $=id=>document.getElementById(id);
function toast(m){const t=$("toast");t.textContent=m;t.style.display="block";setTimeout(()=>t.style.display="none",1800)}
function norm(v){return String(v||"").trim().toLowerCase().replace(/^https?:\/\/(www\.)?instagram\.com\//,"").replace(/^instagram\.com\//,"").replace(/^_u\//,"").replace(/[?#].*$/,"").replace(/^@+/,"").replace(/\/+$/,"").trim()}
function valid(x){return /^[a-z0-9._]{1,30}$/.test(x)&&!["instagram","accounts","explore","direct","p","reels","stories","www","about","privacy","terms","login","_u"].includes(x)}
function uniq(a){const s=new Set();(a||[]).forEach(v=>{v=norm(v);if(valid(v))s.add(v)});return [...s]}
function setNum(id,n){const el=$(id);if(el)el.textContent=String(n)} function setText(id,t){const el=$(id);if(el)el.textContent=t}
function nowTime(){return new Date().toLocaleTimeString("ko-KR",{hour:"2-digit",minute:"2-digit"})} function setGold(status,source){setText("goldStatus",status||"정상");if(source)setText("goldSource",source)} function setRoomTime(){const n=nowTime();localStorage.setItem("yb_room_time",n);setText("goldRoomTime",n)} function loadRoomTime(){setText("goldRoomTime",localStorage.getItem("yb_room_time")||"대기")}
function parseCSV(t){const rows=[];let r=[],c="",q=false;for(let i=0;i<t.length;i++){let ch=t[i],n=t[i+1];if(ch=='"'&&q&&n=='"'){c+='"';i++;continue}if(ch=='"'){q=!q;continue}if(ch==','&&!q){r.push(c);c="";continue}if((ch==='\n'||ch==='\r')&&!q){if(c||r.length){r.push(c);rows.push(r);r=[];c=""}if(ch==='\r'&&n==='\n')i++;continue}c+=ch}if(c||r.length){r.push(c);rows.push(r)}return rows}
function stripHtml(s){return String(s||"").replace(/<br\s*\/?>/gi,"\n").replace(/<[^>]+>/g,"").replace(/&nbsp;/g," ").replace(/&amp;/g,"&").replace(/&lt;/g,"<").replace(/&gt;/g,">").replace(/&#39;/g,"'").replace(/&quot;/g,'"').trim()}
function parseHtmlTable(h){const rows=[];let tr;const trRe=/<tr[\s\S]*?<\/tr>/gi;while((tr=trRe.exec(h))){const row=[];let cell;const cellRe=/<t[dh][\s\S]*?<\/t[dh]>/gi;while((cell=cellRe.exec(tr[0])))row.push(stripHtml(cell[0]));if(row.length)rows.push(row)}return rows}
function rowsToRoom(rows){const data=[];rows.forEach((r,i)=>{const joined=r.join(" ");if(i===0&&(joined.includes("번호")||joined.includes("닉네임")||joined.includes("아이디")))return;const id=norm(r[2]||r[1]||r[0]||"");if(valid(id))data.push({no:r[0]||"",name:r[1]||"",id})});const seen=new Set();return data.filter(x=>!seen.has(x.id)&&seen.add(x.id))}
function applyRoomText(text,source){const rows=/<table|<tr|<td|<th/i.test(text)?parseHtmlTable(text):parseCSV(text);roomList=rowsToRoom(rows);results.roomAll=roomList;localStorage.setItem("yb_room_cache",JSON.stringify(roomList));setNum("roomCount",roomList.length);setText("roomStatus",roomList.length?"최신":"확인");setText("sheetState",roomList.length?"자동연동":"확인필요");setText("roomMsg",roomList.length?`명단 ${roomList.length}명 불러옴 (${source||"저장"})`:"명단을 읽지 못했어요.");if(roomList.length){setRoomTime();setGold("정상",source||"저장")}renderList();return roomList.length}
function showRoomCache(){try{const c=localStorage.getItem("yb_room_cache");if(c){const p=JSON.parse(c)||[];if(p.length){roomList=p;results.roomAll=roomList;setNum("roomCount",roomList.length);setText("roomStatus","저장됨");setText("sheetState","빠른표시");setText("roomMsg",`저장된 명단 ${roomList.length}명 표시 중`);setGold("정상","저장캐시");return true}}catch(e){}setGold("확인중","없음");return false}
function sheetUrls(){const a=[];const saved=localStorage.getItem("yb_sheet_url_override");if(saved)a.push(["관리자시트",saved]);a.push(["GitHub백업",LOCAL_ROOM_URL],["CSV",DEFAULT_SHEET_URL],["GVIZ",BACKUP_SHEET_URL],["HTMLVIEW",HTMLVIEW_SHEET_URL]);return a}
async function fetchAnyText(){let last="";for(const [name,u] of sheetUrls()){try{const joiner=u.includes("?")?"&":"?";const res=await fetch(u+joiner+"t="+Date.now(),{cache:"no-store"});if(!res.ok)throw Error("HTTP "+res.status);const txt=await res.text();if(txt&&txt.length>20)return {txt,source:name}}catch(e){last=name+": "+(e.message||e)}}throw Error(last||"명단 연결 실패")}
async function loadRoomList(show=false){const btn=$("loadRoomBtn");try{if(btn)btn.disabled=true;setGold("확인중","자동확인");setText("sheetState","자동확인");if(!roomList.length)setText("roomStatus","확인중");if(!roomList.length)showRoomCache();const got=await fetchAnyText();const count=applyRoomText(got.txt,got.source);if(show)toast(count?"명단 불러오기 완료":"명단 확인 필요")}catch(e){if(roomList.length){setText("roomStatus","저장됨");setText("sheetState","캐시사용");setText("roomMsg","최신 연동은 실패해서 저장된 명단을 사용 중입니다.");setGold("정상","저장캐시");if(show)toast("저장된 명단 사용")}else{setText("roomStatus","실패");setText("sheetState","오류");setText("roomMsg","명단 연결 실패. 관리자에서 명단을 붙여넣어 저장해주세요.");setGold("오류","연동실패");if(show)toast("명단 연결 실패")}}finally{if(btn)btn.disabled=false}}
function pickFile(zip, exactName){const exact=exactName.toLowerCase();return Object.keys(zip.files).filter(n=>!zip.files[n].dir).find(n=>n.toLowerCase().replace(/\\/g,"/").split("/").pop()===exact)}
function extractHtmlIds(text){let ids=[],m;const href=/href=["']https?:\/\/(?:www\.)?instagram\.com\/(?:_u\/)?([A-Za-z0-9._]+)\/?["']/g;while((m=href.exec(text)))ids.push(m[1]);if(ids.length)return uniq(ids);const url=/https?:\/\/(?:www\.)?instagram\.com\/(?:_u\/)?([A-Za-z0-9._]+)/g;while((m=url.exec(text)))ids.push(m[1]);return uniq(ids)}
function collectJson(o,out){if(!o)return;if(typeof o==="string"){const n=norm(o);if(valid(n))out.push(n);return}if(Array.isArray(o)){o.forEach(x=>collectJson(x,out));return}if(typeof o==="object"){if(o.value)collectJson(o.value,out);if(o.href)collectJson(o.href,out);if(o.username)collectJson(o.username,out);Object.keys(o).forEach(k=>collectJson(o[k],out))}}
function extractJsonIds(text){let ids=[];try{collectJson(JSON.parse(text),ids)}catch(e){}return uniq(ids)}
async function parseZip(file){if(!file)throw Error("ZIP 파일을 선택해주세요.");if(!window.JSZip)throw Error("ZIP 분석 라이브러리를 불러오지 못했어요. 새로고침 해주세요.");const zip=await JSZip.loadAsync(file);const fName=pickFile(zip,"followers_1.html")||pickFile(zip,"followers_1.json");const gName=pickFile(zip,"following.html")||pickFile(zip,"following.json");if(!fName)throw Error("followers_1.html 파일을 찾지 못했어요.");if(!gName)throw Error("following.html 파일을 찾지 못했어요.");const fText=await zip.files[fName].async("string");const gText=await zip.files[gName].async("string");const followers=fName.toLowerCase().endsWith(".json")?extractJsonIds(fText):extractHtmlIds(fText);const following=gName.toLowerCase().endsWith(".json")?extractJsonIds(gText):extractHtmlIds(gText);if(followers.length<10)throw Error("followers_1.html에서 계정을 충분히 읽지 못했어요.");if(following.length<10)throw Error("following.html에서 계정을 충분히 읽지 못했어요.");return {followers,following}}
async function analyze(){const btn=$("analyzeBtn");try{btn.disabled=true;btn.textContent="분석 중...";setText("status","");if(!roomList.length)await loadRoomList(false);if(!roomList.length)throw Error("단톡방 명단을 먼저 불러오거나 저장해주세요.");const pf=parseInt($("currentFollowers").value,10),pg=parseInt($("currentFollowing").value,10);if(!pf||!pg)throw Error("현재 팔로워/팔로잉 숫자를 입력해주세요.");setText("status","ZIP 파일 분석 중...");const parsed=await parseZip($("zipFile").files[0]);const followers=parsed.followers,following=parsed.following;const F=new Set(followers),G=new Set(following);const mutual=following.filter(id=>F.has(id));const onlyMe=following.filter(id=>!F.has(id));const fansOnly=followers.filter(id=>!G.has(id));const roomMutual=roomList.filter(r=>F.has(r.id)&&G.has(r.id));const roomNot=roomList.filter(r=>G.has(r.id)&&!F.has(r.id));const roomFans=roomList.filter(r=>F.has(r.id)&&!G.has(r.id));const roomNotFollowed=roomList.filter(r=>!G.has(r.id));results={roomAll:roomList,roomMutual,roomNot,fansOnly:roomFans,roomNotFollowed,onlyMe:onlyMe.map(id=>({id,name:""}))};setNum("cRoomMutual",roomMutual.length);setNum("cRoomNot",roomNot.length);setNum("cFansOnly",roomFans.length);setNum("cRoomTotal",roomList.length);setNum("sFollowers",followers.length);setNum("sFollowing",following.length);setNum("sMutual",mutual.length);setNum("sOnlyMe",onlyMe.length);setText("doneTime",nowTime());const ok=mutual.length+onlyMe.length===following.length;setText("checkMsg",`검증: 전체 맞팔(${mutual.length}) + 전체 나만 팔로우(${onlyMe.length}) = 팔로잉(${following.length}) / 상대만 나를 팔로우 ${fansOnly.length}명`);setText("goldCheck",ok?"정상":"확인");$("cards").classList.remove("hidden");$("summary").classList.remove("hidden");$("lists").classList.remove("hidden");$("status").innerHTML=`✅ 분석 완료<br>ZIP 팔로워 ${followers.length}명 / ZIP 팔로잉 ${following.length}명`;showTab("roomNot");toast("분석 완료")}catch(e){setText("status","오류: "+e.message);setText("goldCheck","확인");toast("확인 필요")}finally{btn.disabled=false;btn.textContent="🦊 맞팔 분석 시작"}}
function clearNumbers(show=true){$("currentFollowers").value="";$("currentFollowing").value="";if(show)toast("숫자 초기화 완료")}
function showTab(tab){currentTab=tab;document.querySelectorAll(".tab").forEach(b=>b.classList.toggle("active",b.dataset.tab===tab));if(tab==="roomAll")results.roomAll=roomList;renderList()}
function filteredList(){const raw=String($("q").value||"").trim().toLowerCase();const q=norm(raw);const arr=currentTab==="roomAll"?roomList:(results[currentTab]||[]);return arr.filter(x=>{const id=norm(x.id);const name=String(x.name||"").toLowerCase();return !raw||id.includes(q)||name.includes(raw)||name.includes(q)})}
function renderList(){const f=filteredList();$("list").innerHTML=f.map((x,i)=>{const id=norm(x.id);let badge="";if(currentTab==="roomAll")badge="명단";if(currentTab==="roomMutual")badge="맞팔";if(currentTab==="roomNot")badge="상대가 날 안함";if(currentTab==="fansOnly")badge="상대만 나를 팔로우";if(currentTab==="roomNotFollowed")badge="내가 안함";if(currentTab==="onlyMe")badge="상대가 날 안함";return `<div class="item"><span>${i+1}.</span><b>${x.name||""}</b><a href="https://www.instagram.com/${id}/" target="_blank" rel="noopener noreferrer">@${id}</a><small>${badge}</small></div>`}).join("")||"<p class='muted'>현재 선택한 탭에는 결과가 없어요. 시트에 있는 사람만 확인하려면 [전체 명단 검색] 탭을 눌러주세요.</p>"}
function copyCurrent(){const f=filteredList();navigator.clipboard.writeText(f.map((x,i)=>`${i+1}. ${x.name||""} @${norm(x.id)}`).join("\n"));toast("복사 완료")}
function adminLogin(){const pw=$("adminPw").value.trim();if(pw===ADMIN_PASSWORD){$("adminBox").classList.remove("hidden");$("sheetUrl").value=localStorage.getItem("yb_sheet_url_override")||HTMLVIEW_SHEET_URL;setText("adminMsg","관리자 로그인 완료");toast("관리자 로그인 완료")}else toast("비밀번호가 달라요")}
function saveSheet(){const u=$("sheetUrl").value.trim();if(!u){toast("주소를 입력해주세요");return}localStorage.setItem("yb_sheet_url_override",u);localStorage.removeItem("yb_room_cache");setText("adminMsg","시트 주소 저장 완료");loadRoomList(true)}
function resetSheet(){localStorage.removeItem("yb_sheet_url_override");localStorage.removeItem("yb_room_cache");$("sheetUrl").value=HTMLVIEW_SHEET_URL;loadRoomList(true)}
function saveManualList(){const text=$("manualList").value.trim();if(!text){toast("명단을 붙여넣어주세요");return}const count=applyRoomText(text,"수동저장");setText("adminMsg",`붙여넣은 명단 ${count}명 저장 완료`);toast("명단 저장 완료")}
function clearRoomCache(){localStorage.removeItem("yb_room_cache");roomList=[];results.roomAll=[];setNum("roomCount",0);setText("roomStatus","대기");setText("sheetState","대기");setText("roomMsg","저장된 명단 삭제 완료");setGold("정상","삭제됨");toast("삭제 완료")}
function bindEvents(){$("loadRoomBtn").addEventListener("click",()=>loadRoomList(true));$("analyzeBtn").addEventListener("click",analyze);$("clearBtn").addEventListener("click",()=>clearNumbers(true));$("copyBtn").addEventListener("click",copyCurrent);$("q").addEventListener("input",renderList);$("adminLoginBtn").addEventListener("click",adminLogin);$("adminPw").addEventListener("keydown",e=>{if(e.key==="Enter")adminLogin()});$("saveSheetBtn").addEventListener("click",saveSheet);$("resetSheetBtn").addEventListener("click",resetSheet);$("saveManualBtn").addEventListener("click",saveManualList);$("clearRoomBtn").addEventListener("click",clearRoomCache);document.querySelectorAll(".tab").forEach(b=>b.addEventListener("click",()=>showTab(b.dataset.tab)));document.querySelectorAll("nav button").forEach(b=>b.addEventListener("click",()=>{const target=b.dataset.scroll;if(target==="top")scrollTo(0,0);else $(target)?.scrollIntoView({behavior:"smooth"})}));$("installBtn").addEventListener("click",()=>toast("브라우저 메뉴에서 홈 화면에 추가를 눌러주세요"))}
window.addEventListener("load",()=>{bindEvents();clearNumbers(false);loadRoomTime();showRoomCache();setTimeout(()=>loadRoomList(false),120);setTimeout(()=>{if(!roomList.length)loadRoomList(false)},5000)});
window.addEventListener("pageshow",()=>clearNumbers(false));
